#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Зарплата
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Zarplata")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertRemont(Remont instance);
    partial void UpdateRemont(Remont instance);
    partial void DeleteRemont(Remont instance);
    partial void InsertFOT_analise(FOT_analise instance);
    partial void UpdateFOT_analise(FOT_analise instance);
    partial void DeleteFOT_analise(FOT_analise instance);
    partial void InsertBonus_za_ZNR(Bonus_za_ZNR instance);
    partial void UpdateBonus_za_ZNR(Bonus_za_ZNR instance);
    partial void DeleteBonus_za_ZNR(Bonus_za_ZNR instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Зарплата.Properties.Settings.Default.ZarplataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Remont> Remont
		{
			get
			{
				return this.GetTable<Remont>();
			}
		}
		
		public System.Data.Linq.Table<FOT_analise> FOT_analise
		{
			get
			{
				return this.GetTable<FOT_analise>();
			}
		}
		
		public System.Data.Linq.Table<Bonus_za_ZNR> Bonus_za_ZNR
		{
			get
			{
				return this.GetTable<Bonus_za_ZNR>();
			}
		}
		
		public System.Data.Linq.Table<Motivation> Motivation
		{
			get
			{
				return this.GetTable<Motivation>();
			}
		}
		
		public System.Data.Linq.Table<Stavki> Stavki
		{
			get
			{
				return this.GetTable<Stavki>();
			}
		}
		
		public System.Data.Linq.Table<crm_max> crm_max
		{
			get
			{
				return this.GetTable<crm_max>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Remont")]
	public partial class Remont : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Remont_num;
		
		private System.Nullable<long> _Zapros;
		
		private string _Filial;
		
		private string _Klient;
		
		private string _Truck_model;
		
		private string _Prichina;
		
		private string _ZNR_Date_Open;
		
		private string _ZNR_Date_Close;
		
		private System.Nullable<double> _Summa_mat;
		
		private System.Nullable<double> _Summa_trud;
		
		private System.Nullable<double> _Summa_rashod;
		
		private string _Status;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRemont_numChanging(long value);
    partial void OnRemont_numChanged();
    partial void OnZaprosChanging(System.Nullable<long> value);
    partial void OnZaprosChanged();
    partial void OnFilialChanging(string value);
    partial void OnFilialChanged();
    partial void OnKlientChanging(string value);
    partial void OnKlientChanged();
    partial void OnTruck_modelChanging(string value);
    partial void OnTruck_modelChanged();
    partial void OnPrichinaChanging(string value);
    partial void OnPrichinaChanged();
    partial void OnZNR_Date_OpenChanging(string value);
    partial void OnZNR_Date_OpenChanged();
    partial void OnZNR_Date_CloseChanging(string value);
    partial void OnZNR_Date_CloseChanged();
    partial void OnSumma_matChanging(System.Nullable<double> value);
    partial void OnSumma_matChanged();
    partial void OnSumma_trudChanging(System.Nullable<double> value);
    partial void OnSumma_trudChanged();
    partial void OnSumma_rashodChanging(System.Nullable<double> value);
    partial void OnSumma_rashodChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public Remont()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remont_num", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Remont_num
		{
			get
			{
				return this._Remont_num;
			}
			set
			{
				if ((this._Remont_num != value))
				{
					this.OnRemont_numChanging(value);
					this.SendPropertyChanging();
					this._Remont_num = value;
					this.SendPropertyChanged("Remont_num");
					this.OnRemont_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zapros", DbType="BigInt")]
		public System.Nullable<long> Zapros
		{
			get
			{
				return this._Zapros;
			}
			set
			{
				if ((this._Zapros != value))
				{
					this.OnZaprosChanging(value);
					this.SendPropertyChanging();
					this._Zapros = value;
					this.SendPropertyChanged("Zapros");
					this.OnZaprosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filial", DbType="NVarChar(MAX)")]
		public string Filial
		{
			get
			{
				return this._Filial;
			}
			set
			{
				if ((this._Filial != value))
				{
					this.OnFilialChanging(value);
					this.SendPropertyChanging();
					this._Filial = value;
					this.SendPropertyChanged("Filial");
					this.OnFilialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Klient", DbType="NVarChar(MAX)")]
		public string Klient
		{
			get
			{
				return this._Klient;
			}
			set
			{
				if ((this._Klient != value))
				{
					this.OnKlientChanging(value);
					this.SendPropertyChanging();
					this._Klient = value;
					this.SendPropertyChanged("Klient");
					this.OnKlientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truck_model", DbType="NVarChar(MAX)")]
		public string Truck_model
		{
			get
			{
				return this._Truck_model;
			}
			set
			{
				if ((this._Truck_model != value))
				{
					this.OnTruck_modelChanging(value);
					this.SendPropertyChanging();
					this._Truck_model = value;
					this.SendPropertyChanged("Truck_model");
					this.OnTruck_modelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prichina", DbType="NVarChar(MAX)")]
		public string Prichina
		{
			get
			{
				return this._Prichina;
			}
			set
			{
				if ((this._Prichina != value))
				{
					this.OnPrichinaChanging(value);
					this.SendPropertyChanging();
					this._Prichina = value;
					this.SendPropertyChanged("Prichina");
					this.OnPrichinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZNR_Date_Open", DbType="NVarChar(MAX)")]
		public string ZNR_Date_Open
		{
			get
			{
				return this._ZNR_Date_Open;
			}
			set
			{
				if ((this._ZNR_Date_Open != value))
				{
					this.OnZNR_Date_OpenChanging(value);
					this.SendPropertyChanging();
					this._ZNR_Date_Open = value;
					this.SendPropertyChanged("ZNR_Date_Open");
					this.OnZNR_Date_OpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZNR_Date_Close", DbType="NVarChar(MAX)")]
		public string ZNR_Date_Close
		{
			get
			{
				return this._ZNR_Date_Close;
			}
			set
			{
				if ((this._ZNR_Date_Close != value))
				{
					this.OnZNR_Date_CloseChanging(value);
					this.SendPropertyChanging();
					this._ZNR_Date_Close = value;
					this.SendPropertyChanged("ZNR_Date_Close");
					this.OnZNR_Date_CloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summa_mat", DbType="Float")]
		public System.Nullable<double> Summa_mat
		{
			get
			{
				return this._Summa_mat;
			}
			set
			{
				if ((this._Summa_mat != value))
				{
					this.OnSumma_matChanging(value);
					this.SendPropertyChanging();
					this._Summa_mat = value;
					this.SendPropertyChanged("Summa_mat");
					this.OnSumma_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summa_trud", DbType="Float")]
		public System.Nullable<double> Summa_trud
		{
			get
			{
				return this._Summa_trud;
			}
			set
			{
				if ((this._Summa_trud != value))
				{
					this.OnSumma_trudChanging(value);
					this.SendPropertyChanging();
					this._Summa_trud = value;
					this.SendPropertyChanged("Summa_trud");
					this.OnSumma_trudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summa_rashod", DbType="Float")]
		public System.Nullable<double> Summa_rashod
		{
			get
			{
				return this._Summa_rashod;
			}
			set
			{
				if ((this._Summa_rashod != value))
				{
					this.OnSumma_rashodChanging(value);
					this.SendPropertyChanging();
					this._Summa_rashod = value;
					this.SendPropertyChanged("Summa_rashod");
					this.OnSumma_rashodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FOT_analise")]
	public partial class FOT_analise : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _Period;
		
		private System.Nullable<long> _Remont;
		
		private string _Truck;
		
		private string _Klient;
		
		private System.Nullable<double> _Summa_mat;
		
		private System.Nullable<double> _Summa_trud;
		
		private System.Nullable<double> _Summa_rashod;
		
		private System.Nullable<double> _FOT_prod_mat;
		
		private System.Nullable<double> _FOT_prod_trud;
		
		private System.Nullable<double> _FOT_brigad_mat;
		
		private System.Nullable<double> _FOT_brigad_trud;
		
		private System.Nullable<double> _FOT_oform_mat;
		
		private System.Nullable<double> _FOT_oform_trud;
		
		private System.Nullable<double> _FOT_mehan_mat;
		
		private System.Nullable<double> _FOT_mehan_trud;
		
		private System.Nullable<double> _FOT_mehan_rashod;
		
		private System.Nullable<double> _Davnost;
		
		private System.Nullable<double> _Percent_prod_mat;
		
		private System.Nullable<double> _Percent_prod_trud;
		
		private System.Nullable<double> _Percent_brigad_mat;
		
		private System.Nullable<double> _Percent_brigad_trud;
		
		private System.Nullable<double> _Percent_oform_mat;
		
		private System.Nullable<double> _Percent_oform_trud;
		
		private System.Nullable<double> _Percent_mehan_trud;
		
		private System.Nullable<double> _Percent_mehan_rashod;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnPeriodChanging(string value);
    partial void OnPeriodChanged();
    partial void OnRemontChanging(System.Nullable<long> value);
    partial void OnRemontChanged();
    partial void OnTruckChanging(string value);
    partial void OnTruckChanged();
    partial void OnKlientChanging(string value);
    partial void OnKlientChanged();
    partial void OnSumma_matChanging(System.Nullable<double> value);
    partial void OnSumma_matChanged();
    partial void OnSumma_trudChanging(System.Nullable<double> value);
    partial void OnSumma_trudChanged();
    partial void OnSumma_rashodChanging(System.Nullable<double> value);
    partial void OnSumma_rashodChanged();
    partial void OnFOT_prod_matChanging(System.Nullable<double> value);
    partial void OnFOT_prod_matChanged();
    partial void OnFOT_prod_trudChanging(System.Nullable<double> value);
    partial void OnFOT_prod_trudChanged();
    partial void OnFOT_brigad_matChanging(System.Nullable<double> value);
    partial void OnFOT_brigad_matChanged();
    partial void OnFOT_brigad_trudChanging(System.Nullable<double> value);
    partial void OnFOT_brigad_trudChanged();
    partial void OnFOT_oform_matChanging(System.Nullable<double> value);
    partial void OnFOT_oform_matChanged();
    partial void OnFOT_oform_trudChanging(System.Nullable<double> value);
    partial void OnFOT_oform_trudChanged();
    partial void OnFOT_mehan_matChanging(System.Nullable<double> value);
    partial void OnFOT_mehan_matChanged();
    partial void OnFOT_mehan_trudChanging(System.Nullable<double> value);
    partial void OnFOT_mehan_trudChanged();
    partial void OnFOT_mehan_rashodChanging(System.Nullable<double> value);
    partial void OnFOT_mehan_rashodChanged();
    partial void OnDavnostChanging(System.Nullable<double> value);
    partial void OnDavnostChanged();
    partial void OnPercent_prod_matChanging(System.Nullable<double> value);
    partial void OnPercent_prod_matChanged();
    partial void OnPercent_prod_trudChanging(System.Nullable<double> value);
    partial void OnPercent_prod_trudChanged();
    partial void OnPercent_brigad_matChanging(System.Nullable<double> value);
    partial void OnPercent_brigad_matChanged();
    partial void OnPercent_brigad_trudChanging(System.Nullable<double> value);
    partial void OnPercent_brigad_trudChanged();
    partial void OnPercent_oform_matChanging(System.Nullable<double> value);
    partial void OnPercent_oform_matChanged();
    partial void OnPercent_oform_trudChanging(System.Nullable<double> value);
    partial void OnPercent_oform_trudChanged();
    partial void OnPercent_mehan_trudChanging(System.Nullable<double> value);
    partial void OnPercent_mehan_trudChanged();
    partial void OnPercent_mehan_rashodChanging(System.Nullable<double> value);
    partial void OnPercent_mehan_rashodChanged();
    #endregion
		
		public FOT_analise()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="NChar(10)")]
		public string Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this.OnPeriodChanging(value);
					this.SendPropertyChanging();
					this._Period = value;
					this.SendPropertyChanged("Period");
					this.OnPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remont", DbType="BigInt")]
		public System.Nullable<long> Remont
		{
			get
			{
				return this._Remont;
			}
			set
			{
				if ((this._Remont != value))
				{
					this.OnRemontChanging(value);
					this.SendPropertyChanging();
					this._Remont = value;
					this.SendPropertyChanged("Remont");
					this.OnRemontChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truck", DbType="NVarChar(50)")]
		public string Truck
		{
			get
			{
				return this._Truck;
			}
			set
			{
				if ((this._Truck != value))
				{
					this.OnTruckChanging(value);
					this.SendPropertyChanging();
					this._Truck = value;
					this.SendPropertyChanged("Truck");
					this.OnTruckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Klient", DbType="NVarChar(MAX)")]
		public string Klient
		{
			get
			{
				return this._Klient;
			}
			set
			{
				if ((this._Klient != value))
				{
					this.OnKlientChanging(value);
					this.SendPropertyChanging();
					this._Klient = value;
					this.SendPropertyChanged("Klient");
					this.OnKlientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summa_mat", DbType="Float")]
		public System.Nullable<double> Summa_mat
		{
			get
			{
				return this._Summa_mat;
			}
			set
			{
				if ((this._Summa_mat != value))
				{
					this.OnSumma_matChanging(value);
					this.SendPropertyChanging();
					this._Summa_mat = value;
					this.SendPropertyChanged("Summa_mat");
					this.OnSumma_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summa_trud", DbType="Float")]
		public System.Nullable<double> Summa_trud
		{
			get
			{
				return this._Summa_trud;
			}
			set
			{
				if ((this._Summa_trud != value))
				{
					this.OnSumma_trudChanging(value);
					this.SendPropertyChanging();
					this._Summa_trud = value;
					this.SendPropertyChanged("Summa_trud");
					this.OnSumma_trudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summa_rashod", DbType="Float")]
		public System.Nullable<double> Summa_rashod
		{
			get
			{
				return this._Summa_rashod;
			}
			set
			{
				if ((this._Summa_rashod != value))
				{
					this.OnSumma_rashodChanging(value);
					this.SendPropertyChanging();
					this._Summa_rashod = value;
					this.SendPropertyChanged("Summa_rashod");
					this.OnSumma_rashodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOT_prod_mat", DbType="Float")]
		public System.Nullable<double> FOT_prod_mat
		{
			get
			{
				return this._FOT_prod_mat;
			}
			set
			{
				if ((this._FOT_prod_mat != value))
				{
					this.OnFOT_prod_matChanging(value);
					this.SendPropertyChanging();
					this._FOT_prod_mat = value;
					this.SendPropertyChanged("FOT_prod_mat");
					this.OnFOT_prod_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOT_prod_trud", DbType="Float")]
		public System.Nullable<double> FOT_prod_trud
		{
			get
			{
				return this._FOT_prod_trud;
			}
			set
			{
				if ((this._FOT_prod_trud != value))
				{
					this.OnFOT_prod_trudChanging(value);
					this.SendPropertyChanging();
					this._FOT_prod_trud = value;
					this.SendPropertyChanged("FOT_prod_trud");
					this.OnFOT_prod_trudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOT_brigad_mat", DbType="Float")]
		public System.Nullable<double> FOT_brigad_mat
		{
			get
			{
				return this._FOT_brigad_mat;
			}
			set
			{
				if ((this._FOT_brigad_mat != value))
				{
					this.OnFOT_brigad_matChanging(value);
					this.SendPropertyChanging();
					this._FOT_brigad_mat = value;
					this.SendPropertyChanged("FOT_brigad_mat");
					this.OnFOT_brigad_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOT_brigad_trud", DbType="Float")]
		public System.Nullable<double> FOT_brigad_trud
		{
			get
			{
				return this._FOT_brigad_trud;
			}
			set
			{
				if ((this._FOT_brigad_trud != value))
				{
					this.OnFOT_brigad_trudChanging(value);
					this.SendPropertyChanging();
					this._FOT_brigad_trud = value;
					this.SendPropertyChanged("FOT_brigad_trud");
					this.OnFOT_brigad_trudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOT_oform_mat", DbType="Float")]
		public System.Nullable<double> FOT_oform_mat
		{
			get
			{
				return this._FOT_oform_mat;
			}
			set
			{
				if ((this._FOT_oform_mat != value))
				{
					this.OnFOT_oform_matChanging(value);
					this.SendPropertyChanging();
					this._FOT_oform_mat = value;
					this.SendPropertyChanged("FOT_oform_mat");
					this.OnFOT_oform_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOT_oform_trud", DbType="Float")]
		public System.Nullable<double> FOT_oform_trud
		{
			get
			{
				return this._FOT_oform_trud;
			}
			set
			{
				if ((this._FOT_oform_trud != value))
				{
					this.OnFOT_oform_trudChanging(value);
					this.SendPropertyChanging();
					this._FOT_oform_trud = value;
					this.SendPropertyChanged("FOT_oform_trud");
					this.OnFOT_oform_trudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOT_mehan_mat", DbType="Float")]
		public System.Nullable<double> FOT_mehan_mat
		{
			get
			{
				return this._FOT_mehan_mat;
			}
			set
			{
				if ((this._FOT_mehan_mat != value))
				{
					this.OnFOT_mehan_matChanging(value);
					this.SendPropertyChanging();
					this._FOT_mehan_mat = value;
					this.SendPropertyChanged("FOT_mehan_mat");
					this.OnFOT_mehan_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOT_mehan_trud", DbType="Float")]
		public System.Nullable<double> FOT_mehan_trud
		{
			get
			{
				return this._FOT_mehan_trud;
			}
			set
			{
				if ((this._FOT_mehan_trud != value))
				{
					this.OnFOT_mehan_trudChanging(value);
					this.SendPropertyChanging();
					this._FOT_mehan_trud = value;
					this.SendPropertyChanged("FOT_mehan_trud");
					this.OnFOT_mehan_trudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOT_mehan_rashod", DbType="Float")]
		public System.Nullable<double> FOT_mehan_rashod
		{
			get
			{
				return this._FOT_mehan_rashod;
			}
			set
			{
				if ((this._FOT_mehan_rashod != value))
				{
					this.OnFOT_mehan_rashodChanging(value);
					this.SendPropertyChanging();
					this._FOT_mehan_rashod = value;
					this.SendPropertyChanged("FOT_mehan_rashod");
					this.OnFOT_mehan_rashodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Davnost", DbType="Float")]
		public System.Nullable<double> Davnost
		{
			get
			{
				return this._Davnost;
			}
			set
			{
				if ((this._Davnost != value))
				{
					this.OnDavnostChanging(value);
					this.SendPropertyChanging();
					this._Davnost = value;
					this.SendPropertyChanged("Davnost");
					this.OnDavnostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Percent_prod_mat", DbType="Float")]
		public System.Nullable<double> Percent_prod_mat
		{
			get
			{
				return this._Percent_prod_mat;
			}
			set
			{
				if ((this._Percent_prod_mat != value))
				{
					this.OnPercent_prod_matChanging(value);
					this.SendPropertyChanging();
					this._Percent_prod_mat = value;
					this.SendPropertyChanged("Percent_prod_mat");
					this.OnPercent_prod_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Percent_prod_trud", DbType="Float")]
		public System.Nullable<double> Percent_prod_trud
		{
			get
			{
				return this._Percent_prod_trud;
			}
			set
			{
				if ((this._Percent_prod_trud != value))
				{
					this.OnPercent_prod_trudChanging(value);
					this.SendPropertyChanging();
					this._Percent_prod_trud = value;
					this.SendPropertyChanged("Percent_prod_trud");
					this.OnPercent_prod_trudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Percent_brigad_mat", DbType="Float")]
		public System.Nullable<double> Percent_brigad_mat
		{
			get
			{
				return this._Percent_brigad_mat;
			}
			set
			{
				if ((this._Percent_brigad_mat != value))
				{
					this.OnPercent_brigad_matChanging(value);
					this.SendPropertyChanging();
					this._Percent_brigad_mat = value;
					this.SendPropertyChanged("Percent_brigad_mat");
					this.OnPercent_brigad_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Percent_brigad_trud", DbType="Float")]
		public System.Nullable<double> Percent_brigad_trud
		{
			get
			{
				return this._Percent_brigad_trud;
			}
			set
			{
				if ((this._Percent_brigad_trud != value))
				{
					this.OnPercent_brigad_trudChanging(value);
					this.SendPropertyChanging();
					this._Percent_brigad_trud = value;
					this.SendPropertyChanged("Percent_brigad_trud");
					this.OnPercent_brigad_trudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Percent_oform_mat", DbType="Float")]
		public System.Nullable<double> Percent_oform_mat
		{
			get
			{
				return this._Percent_oform_mat;
			}
			set
			{
				if ((this._Percent_oform_mat != value))
				{
					this.OnPercent_oform_matChanging(value);
					this.SendPropertyChanging();
					this._Percent_oform_mat = value;
					this.SendPropertyChanged("Percent_oform_mat");
					this.OnPercent_oform_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Percent_oform_trud", DbType="Float")]
		public System.Nullable<double> Percent_oform_trud
		{
			get
			{
				return this._Percent_oform_trud;
			}
			set
			{
				if ((this._Percent_oform_trud != value))
				{
					this.OnPercent_oform_trudChanging(value);
					this.SendPropertyChanging();
					this._Percent_oform_trud = value;
					this.SendPropertyChanged("Percent_oform_trud");
					this.OnPercent_oform_trudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Percent_mehan_trud", DbType="Float")]
		public System.Nullable<double> Percent_mehan_trud
		{
			get
			{
				return this._Percent_mehan_trud;
			}
			set
			{
				if ((this._Percent_mehan_trud != value))
				{
					this.OnPercent_mehan_trudChanging(value);
					this.SendPropertyChanging();
					this._Percent_mehan_trud = value;
					this.SendPropertyChanged("Percent_mehan_trud");
					this.OnPercent_mehan_trudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Percent_mehan_rashod", DbType="Float")]
		public System.Nullable<double> Percent_mehan_rashod
		{
			get
			{
				return this._Percent_mehan_rashod;
			}
			set
			{
				if ((this._Percent_mehan_rashod != value))
				{
					this.OnPercent_mehan_rashodChanging(value);
					this.SendPropertyChanging();
					this._Percent_mehan_rashod = value;
					this.SendPropertyChanged("Percent_mehan_rashod");
					this.OnPercent_mehan_rashodChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bonus_za_ZNR")]
	public partial class Bonus_za_ZNR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _Period;
		
		private string _FIO;
		
		private string _Dolzhnost;
		
		private string _Filial;
		
		private System.Nullable<int> _Zapros;
		
		private System.Nullable<int> _Remont;
		
		private System.Nullable<double> _Sum_klient;
		
		private System.Nullable<double> _Sum_TSK;
		
		private string _Role;
		
		private System.Nullable<double> _KTU;
		
		private System.Nullable<double> _Davnost;
		
		private string _Srok;
		
		private System.Nullable<double> _Bonus;
		
		private System.Nullable<double> _Percent;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnPeriodChanging(string value);
    partial void OnPeriodChanged();
    partial void OnFIOChanging(string value);
    partial void OnFIOChanged();
    partial void OnDolzhnostChanging(string value);
    partial void OnDolzhnostChanged();
    partial void OnFilialChanging(string value);
    partial void OnFilialChanged();
    partial void OnZaprosChanging(System.Nullable<int> value);
    partial void OnZaprosChanged();
    partial void OnRemontChanging(System.Nullable<int> value);
    partial void OnRemontChanged();
    partial void OnSum_klientChanging(System.Nullable<double> value);
    partial void OnSum_klientChanged();
    partial void OnSum_TSKChanging(System.Nullable<double> value);
    partial void OnSum_TSKChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnKTUChanging(System.Nullable<double> value);
    partial void OnKTUChanged();
    partial void OnDavnostChanging(System.Nullable<double> value);
    partial void OnDavnostChanged();
    partial void OnSrokChanging(string value);
    partial void OnSrokChanged();
    partial void OnBonusChanging(System.Nullable<double> value);
    partial void OnBonusChanged();
    partial void OnPercentChanging(System.Nullable<double> value);
    partial void OnPercentChanged();
    #endregion
		
		public Bonus_za_ZNR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="NVarChar(50)")]
		public string Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this.OnPeriodChanging(value);
					this.SendPropertyChanging();
					this._Period = value;
					this.SendPropertyChanged("Period");
					this.OnPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIO", DbType="NVarChar(50)")]
		public string FIO
		{
			get
			{
				return this._FIO;
			}
			set
			{
				if ((this._FIO != value))
				{
					this.OnFIOChanging(value);
					this.SendPropertyChanging();
					this._FIO = value;
					this.SendPropertyChanged("FIO");
					this.OnFIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dolzhnost", DbType="VarChar(MAX)")]
		public string Dolzhnost
		{
			get
			{
				return this._Dolzhnost;
			}
			set
			{
				if ((this._Dolzhnost != value))
				{
					this.OnDolzhnostChanging(value);
					this.SendPropertyChanging();
					this._Dolzhnost = value;
					this.SendPropertyChanged("Dolzhnost");
					this.OnDolzhnostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filial", DbType="NVarChar(50)")]
		public string Filial
		{
			get
			{
				return this._Filial;
			}
			set
			{
				if ((this._Filial != value))
				{
					this.OnFilialChanging(value);
					this.SendPropertyChanging();
					this._Filial = value;
					this.SendPropertyChanged("Filial");
					this.OnFilialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zapros", DbType="Int")]
		public System.Nullable<int> Zapros
		{
			get
			{
				return this._Zapros;
			}
			set
			{
				if ((this._Zapros != value))
				{
					this.OnZaprosChanging(value);
					this.SendPropertyChanging();
					this._Zapros = value;
					this.SendPropertyChanged("Zapros");
					this.OnZaprosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remont", DbType="Int")]
		public System.Nullable<int> Remont
		{
			get
			{
				return this._Remont;
			}
			set
			{
				if ((this._Remont != value))
				{
					this.OnRemontChanging(value);
					this.SendPropertyChanging();
					this._Remont = value;
					this.SendPropertyChanged("Remont");
					this.OnRemontChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum_klient", DbType="Float")]
		public System.Nullable<double> Sum_klient
		{
			get
			{
				return this._Sum_klient;
			}
			set
			{
				if ((this._Sum_klient != value))
				{
					this.OnSum_klientChanging(value);
					this.SendPropertyChanging();
					this._Sum_klient = value;
					this.SendPropertyChanged("Sum_klient");
					this.OnSum_klientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sum_TSK", DbType="Float")]
		public System.Nullable<double> Sum_TSK
		{
			get
			{
				return this._Sum_TSK;
			}
			set
			{
				if ((this._Sum_TSK != value))
				{
					this.OnSum_TSKChanging(value);
					this.SendPropertyChanging();
					this._Sum_TSK = value;
					this.SendPropertyChanged("Sum_TSK");
					this.OnSum_TSKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(50)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KTU", DbType="Float")]
		public System.Nullable<double> KTU
		{
			get
			{
				return this._KTU;
			}
			set
			{
				if ((this._KTU != value))
				{
					this.OnKTUChanging(value);
					this.SendPropertyChanging();
					this._KTU = value;
					this.SendPropertyChanged("KTU");
					this.OnKTUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Davnost", DbType="Float")]
		public System.Nullable<double> Davnost
		{
			get
			{
				return this._Davnost;
			}
			set
			{
				if ((this._Davnost != value))
				{
					this.OnDavnostChanging(value);
					this.SendPropertyChanging();
					this._Davnost = value;
					this.SendPropertyChanged("Davnost");
					this.OnDavnostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Srok", DbType="NVarChar(50)")]
		public string Srok
		{
			get
			{
				return this._Srok;
			}
			set
			{
				if ((this._Srok != value))
				{
					this.OnSrokChanging(value);
					this.SendPropertyChanging();
					this._Srok = value;
					this.SendPropertyChanged("Srok");
					this.OnSrokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bonus", DbType="Float")]
		public System.Nullable<double> Bonus
		{
			get
			{
				return this._Bonus;
			}
			set
			{
				if ((this._Bonus != value))
				{
					this.OnBonusChanging(value);
					this.SendPropertyChanging();
					this._Bonus = value;
					this.SendPropertyChanged("Bonus");
					this.OnBonusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Percent]", Storage="_Percent", DbType="Float")]
		public System.Nullable<double> Percent
		{
			get
			{
				return this._Percent;
			}
			set
			{
				if ((this._Percent != value))
				{
					this.OnPercentChanging(value);
					this.SendPropertyChanging();
					this._Percent = value;
					this.SendPropertyChanged("Percent");
					this.OnPercentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Motivation")]
	public partial class Motivation
	{
		
		private string _kurator_fio;
		
		private System.Nullable<short> _kurator_id;
		
		private string _kurator_filial;
		
		private string _Period;
		
		private System.Nullable<short> _prod_count;
		
		private System.Nullable<short> _plan_viezd;
		
		private System.Nullable<short> _fact_viezd;
		
		private System.Nullable<short> _fact_viezd_max;
		
		private System.Nullable<short> _plan_zvonok;
		
		private System.Nullable<short> _fact_zvonok;
		
		private System.Nullable<short> _plan_smeta;
		
		private System.Nullable<short> _fact_smeta;
		
		private System.Nullable<double> _fact_zakr;
		
		private System.Nullable<double> _plan_zakr;
		
		private System.Nullable<double> _net_od;
		
		private System.Nullable<double> _debitora;
		
		private System.Nullable<short> _mehan_count;
		
		private System.Nullable<double> _virabotka;
		
		private System.Nullable<double> _vnutr_zakr;
		
		public Motivation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kurator_fio", DbType="NVarChar(MAX)")]
		public string kurator_fio
		{
			get
			{
				return this._kurator_fio;
			}
			set
			{
				if ((this._kurator_fio != value))
				{
					this._kurator_fio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kurator_id", DbType="SmallInt")]
		public System.Nullable<short> kurator_id
		{
			get
			{
				return this._kurator_id;
			}
			set
			{
				if ((this._kurator_id != value))
				{
					this._kurator_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kurator_filial", DbType="NVarChar(MAX)")]
		public string kurator_filial
		{
			get
			{
				return this._kurator_filial;
			}
			set
			{
				if ((this._kurator_filial != value))
				{
					this._kurator_filial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="NVarChar(50)")]
		public string Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this._Period = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prod_count", DbType="SmallInt")]
		public System.Nullable<short> prod_count
		{
			get
			{
				return this._prod_count;
			}
			set
			{
				if ((this._prod_count != value))
				{
					this._prod_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_viezd", DbType="SmallInt")]
		public System.Nullable<short> plan_viezd
		{
			get
			{
				return this._plan_viezd;
			}
			set
			{
				if ((this._plan_viezd != value))
				{
					this._plan_viezd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fact_viezd", DbType="SmallInt")]
		public System.Nullable<short> fact_viezd
		{
			get
			{
				return this._fact_viezd;
			}
			set
			{
				if ((this._fact_viezd != value))
				{
					this._fact_viezd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fact_viezd_max", DbType="SmallInt")]
		public System.Nullable<short> fact_viezd_max
		{
			get
			{
				return this._fact_viezd_max;
			}
			set
			{
				if ((this._fact_viezd_max != value))
				{
					this._fact_viezd_max = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_zvonok", DbType="SmallInt")]
		public System.Nullable<short> plan_zvonok
		{
			get
			{
				return this._plan_zvonok;
			}
			set
			{
				if ((this._plan_zvonok != value))
				{
					this._plan_zvonok = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fact_zvonok", DbType="SmallInt")]
		public System.Nullable<short> fact_zvonok
		{
			get
			{
				return this._fact_zvonok;
			}
			set
			{
				if ((this._fact_zvonok != value))
				{
					this._fact_zvonok = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_smeta", DbType="SmallInt")]
		public System.Nullable<short> plan_smeta
		{
			get
			{
				return this._plan_smeta;
			}
			set
			{
				if ((this._plan_smeta != value))
				{
					this._plan_smeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fact_smeta", DbType="SmallInt")]
		public System.Nullable<short> fact_smeta
		{
			get
			{
				return this._fact_smeta;
			}
			set
			{
				if ((this._fact_smeta != value))
				{
					this._fact_smeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fact_zakr", DbType="Float")]
		public System.Nullable<double> fact_zakr
		{
			get
			{
				return this._fact_zakr;
			}
			set
			{
				if ((this._fact_zakr != value))
				{
					this._fact_zakr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_zakr", DbType="Float")]
		public System.Nullable<double> plan_zakr
		{
			get
			{
				return this._plan_zakr;
			}
			set
			{
				if ((this._plan_zakr != value))
				{
					this._plan_zakr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_net_od", DbType="Float")]
		public System.Nullable<double> net_od
		{
			get
			{
				return this._net_od;
			}
			set
			{
				if ((this._net_od != value))
				{
					this._net_od = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_debitora", DbType="Float")]
		public System.Nullable<double> debitora
		{
			get
			{
				return this._debitora;
			}
			set
			{
				if ((this._debitora != value))
				{
					this._debitora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mehan_count", DbType="SmallInt")]
		public System.Nullable<short> mehan_count
		{
			get
			{
				return this._mehan_count;
			}
			set
			{
				if ((this._mehan_count != value))
				{
					this._mehan_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_virabotka", DbType="Float")]
		public System.Nullable<double> virabotka
		{
			get
			{
				return this._virabotka;
			}
			set
			{
				if ((this._virabotka != value))
				{
					this._virabotka = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vnutr_zakr", DbType="Float")]
		public System.Nullable<double> vnutr_zakr
		{
			get
			{
				return this._vnutr_zakr;
			}
			set
			{
				if ((this._vnutr_zakr != value))
				{
					this._vnutr_zakr = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stavki")]
	public partial class Stavki
	{
		
		private System.Nullable<short> _Tab_num;
		
		private string _FIO;
		
		private System.Nullable<int> _Oklad;
		
		private string _Period;
		
		public Stavki()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tab_num", DbType="SmallInt")]
		public System.Nullable<short> Tab_num
		{
			get
			{
				return this._Tab_num;
			}
			set
			{
				if ((this._Tab_num != value))
				{
					this._Tab_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIO", DbType="NVarChar(50)")]
		public string FIO
		{
			get
			{
				return this._FIO;
			}
			set
			{
				if ((this._FIO != value))
				{
					this._FIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oklad", DbType="Int")]
		public System.Nullable<int> Oklad
		{
			get
			{
				return this._Oklad;
			}
			set
			{
				if ((this._Oklad != value))
				{
					this._Oklad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="NVarChar(50)")]
		public string Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this._Period = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.crm_max")]
	public partial class crm_max
	{
		
		private System.Nullable<short> _Tab_num;
		
		private string _Filial;
		
		private System.Nullable<short> _viezd_vsego;
		
		private System.Nullable<short> _viezd_pers;
		
		private string _Period;
		
		public crm_max()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tab_num", DbType="SmallInt")]
		public System.Nullable<short> Tab_num
		{
			get
			{
				return this._Tab_num;
			}
			set
			{
				if ((this._Tab_num != value))
				{
					this._Tab_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filial", DbType="NVarChar(50)")]
		public string Filial
		{
			get
			{
				return this._Filial;
			}
			set
			{
				if ((this._Filial != value))
				{
					this._Filial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viezd_vsego", DbType="SmallInt")]
		public System.Nullable<short> viezd_vsego
		{
			get
			{
				return this._viezd_vsego;
			}
			set
			{
				if ((this._viezd_vsego != value))
				{
					this._viezd_vsego = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viezd_pers", DbType="SmallInt")]
		public System.Nullable<short> viezd_pers
		{
			get
			{
				return this._viezd_pers;
			}
			set
			{
				if ((this._viezd_pers != value))
				{
					this._viezd_pers = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="NVarChar(50)")]
		public string Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this._Period = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
